version: "3"

services:
  jenkins:
    image: jenkins-with-plugins
    build: .
    ports:
      - 8080:8080
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    healthcheck:
      test: curl -s http://localhost:8080/login
      timeout: 30s
      retries: 10
