FROM alpine:3.15.0@sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3

LABEL org.opencontainers.image.author="d3adb5" \
      org.label-schema.description="A container image for my personal builds!" \
      org.label-schema.version="1.0"

RUN apk update && apk add curl git patch
