version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf.d:/etc/nginx/conf.d
    healthcheck:
      test: curl -s http://localhost
      timeout: 30s
      retries: 10
